env:
  global:
    - DASHBOARD_RPM="f5-neutron-lbaas-dashboard-$(cat f5-version.txt)-1.el7.noarch.rpm"
language: python

python:
    - "2.7"

node_js: 4

install:
  - pip install tox

jobs:
  include:
    - stage: openstack-tox-pep8
      script: tox -e pep8 -vv
    - stage: openstack-tox-py27
      script: echo "Skip py27"
    - stage: build-openstack-sphinx-docs
      script: tox -e docs -vv
    - stage: nodejs-npm-run-lint
      script: tox -e eslint -vv
    - stage: nodejs-npm-run-test
      script: tox -e karma -vv
    - stage: trigger-fvt
      script: ./trigger-fvt.sh
    - stage: build-deploy-rpm
      services: docker
      script:
        - CMD="yum install -y rpm-build rpmdevtools python-setuptools git ; rpmdev-setuptree ; cd /build ; ./build_rpm.sh"
        - docker run --rm -v $(pwd):/build centos:7.5.1804 /bin/bash -c "${CMD}"
        - cp dist/${DASHBOARD_RPM} ./
        - md5sum ${DASHBOARD_RPM} | tee ${DASHBOARD_RPM}.md5
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file:
          - ${DASHBOARD_RPM}
          - ${DASHBOARD_RPM}.md5
        skip_cleanup: true
        overwrite: true
        on:
          tags: true
          condition: ${TRAVIS_TAG} = v*
