- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - openstack-python36-jobs-horizon
      - publish-openstack-docs-pti
    check:
      jobs:
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            required-projects:
              - openstack/horizon

